services:
  parcelec:
    image: ghcr.io/thomas-god/parcelec-app:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.parcelec.loadbalancer.server.port=9002"
      - "traefik.http.routers.parcelec.rule=Host(`parcelec.org`) && PathPrefix(`/api`)"
      - "traefik.http.routers.parcelec.entrypoints=websecure"
      - "traefik.http.routers.parcelec.tls.certresolver=myresolver"
      - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public
    deploy:
      update_config:
        order: start-first

  client:
    image: ghcr.io/thomas-god/parcelec-client:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.client.loadbalancer.server.port=80"
      - "traefik.http.routers.client.rule=Host(`parcelec.org`)"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.routers.client.tls.certresolver=myresolver"
      - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public

volumes:
  letsencrypt:

networks:
  traefik-public:
    external: true
