services:
  traefik:
    image: traefik:v3.1
    command:
      - "--log.level=DEBUG"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-public

  parcelec:
    image: ghcr.io/thomas-god/parcelec-app:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.parcelec.loadbalancer.server.port=9002"
      - "traefik.http.routers.parcelec.rule=Host(`parcelec.org`) && PathPrefix(`/api`)"
      - "traefik.http.routers.parcelec.entrypoints=websecure"
      - "traefik.http.routers.parcelec.tls.certresolver=myresolver"
    deploy:
      update_config:
        order: start-first
    networks:
      - traefik-public

  client:
    image: ghcr.io/thomas-god/parcelec-client:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.client.loadbalancer.server.port=80"
      - "traefik.http.routers.client.rule=Host(`parcelec.org`)"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.routers.client.tls.certresolver=myresolver"
    networks:
      - traefik-public

volumes:
  letsencrypt:

networks:
  traefik-public:
    external: true
