version: "3"
services:
  db:
    volumes:
      - ./db/data:/var/lib/postgresql/data
  test_agent:
    build:
      context: .
      args:
        - NODE_ENV=development
    environment:
      API_URL: http://server:3000
    entrypoint: npx jest -c jest.integration.config.js --detectOpenHandles
