version: "3"
services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=parcelec
    ports:
      - "10100:5432"
  init:
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    environment:
      - ENV=test
      - DATABASE_URL=postgresql://user:password@db/parcelec
    command: >
      sh -c "/root/wait-for-it.sh -t 90 db:5432
      && npm run db-migrate-up"
    links:
      - db