
name: API tests

on:
  pull_request:
    branches:
      - 'feature/**'
      - 'hotfix/**'
  push:
    branches:
      - "develop"

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v2
      - name: Run the API tests suite in a Docker environment
        run: npm run test-docker
