name: Server UnitTests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run test:unit
